// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiBtp.Btp
{
    public static class GetGlobalaccountRoleCollections
    {
        /// <summary>
        /// Gets all role collections.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Btp = Pulumi.Btp;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Btp.GetGlobalaccountRoleCollections.Invoke();
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetGlobalaccountRoleCollectionsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetGlobalaccountRoleCollectionsResult>("btp:index/getGlobalaccountRoleCollections:getGlobalaccountRoleCollections", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Gets all role collections.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Btp = Pulumi.Btp;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Btp.GetGlobalaccountRoleCollections.Invoke();
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetGlobalaccountRoleCollectionsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetGlobalaccountRoleCollectionsResult>("btp:index/getGlobalaccountRoleCollections:getGlobalaccountRoleCollections", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetGlobalaccountRoleCollectionsResult
    {
        /// <summary>
        /// The ID of the global account
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetGlobalaccountRoleCollectionsValueResult> Values;

        [OutputConstructor]
        private GetGlobalaccountRoleCollectionsResult(
            string id,

            ImmutableArray<Outputs.GetGlobalaccountRoleCollectionsValueResult> values)
        {
            Id = id;
            Values = values;
        }
    }
}
