// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiBtp.Btp
{
    /// <summary>
    /// Assigns a user or a group to a role collection on global account level.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Btp = PulumiBtp.Btp;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // assign a user to a role collection on global account level
    ///     var jd = new Btp.GlobalaccountRoleCollectionAssignment("jd", new()
    ///     {
    ///         RoleCollectionName = "Global Account Viewer",
    ///         UserName = "john.doe@mycompany.com",
    ///     });
    /// 
    ///     // assign a group to a role collection on global account level
    ///     var globalaccountViewerGroup = new Btp.GlobalaccountRoleCollectionAssignment("globalaccountViewerGroup", new()
    ///     {
    ///         GroupName = "globalaccount-viewer-group",
    ///         RoleCollectionName = "Global Account Viewer",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [BtpResourceType("btp:index/globalaccountRoleCollectionAssignment:GlobalaccountRoleCollectionAssignment")]
    public partial class GlobalaccountRoleCollectionAssignment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the attribute to assign.
        /// </summary>
        [Output("attributeName")]
        public Output<string?> AttributeName { get; private set; } = null!;

        /// <summary>
        /// The value of the attribute to assign.
        /// </summary>
        [Output("attributeValue")]
        public Output<string?> AttributeValue { get; private set; } = null!;

        /// <summary>
        /// The name of the group to assign.
        /// </summary>
        [Output("groupName")]
        public Output<string?> GroupName { get; private set; } = null!;

        /// <summary>
        /// The identity provider that hosts the user or group. The default value is `ldap`.
        /// </summary>
        [Output("origin")]
        public Output<string> Origin { get; private set; } = null!;

        /// <summary>
        /// The name of the role collection.
        /// </summary>
        [Output("roleCollectionName")]
        public Output<string> RoleCollectionName { get; private set; } = null!;

        /// <summary>
        /// The name of the user to assign.
        /// </summary>
        [Output("userName")]
        public Output<string?> UserName { get; private set; } = null!;


        /// <summary>
        /// Create a GlobalaccountRoleCollectionAssignment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GlobalaccountRoleCollectionAssignment(string name, GlobalaccountRoleCollectionAssignmentArgs args, CustomResourceOptions? options = null)
            : base("btp:index/globalaccountRoleCollectionAssignment:GlobalaccountRoleCollectionAssignment", name, args ?? new GlobalaccountRoleCollectionAssignmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private GlobalaccountRoleCollectionAssignment(string name, Input<string> id, GlobalaccountRoleCollectionAssignmentState? state = null, CustomResourceOptions? options = null)
            : base("btp:index/globalaccountRoleCollectionAssignment:GlobalaccountRoleCollectionAssignment", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lechnerc77/pulumi-btp",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing GlobalaccountRoleCollectionAssignment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static GlobalaccountRoleCollectionAssignment Get(string name, Input<string> id, GlobalaccountRoleCollectionAssignmentState? state = null, CustomResourceOptions? options = null)
        {
            return new GlobalaccountRoleCollectionAssignment(name, id, state, options);
        }
    }

    public sealed class GlobalaccountRoleCollectionAssignmentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the attribute to assign.
        /// </summary>
        [Input("attributeName")]
        public Input<string>? AttributeName { get; set; }

        /// <summary>
        /// The value of the attribute to assign.
        /// </summary>
        [Input("attributeValue")]
        public Input<string>? AttributeValue { get; set; }

        /// <summary>
        /// The name of the group to assign.
        /// </summary>
        [Input("groupName")]
        public Input<string>? GroupName { get; set; }

        /// <summary>
        /// The identity provider that hosts the user or group. The default value is `ldap`.
        /// </summary>
        [Input("origin")]
        public Input<string>? Origin { get; set; }

        /// <summary>
        /// The name of the role collection.
        /// </summary>
        [Input("roleCollectionName", required: true)]
        public Input<string> RoleCollectionName { get; set; } = null!;

        /// <summary>
        /// The name of the user to assign.
        /// </summary>
        [Input("userName")]
        public Input<string>? UserName { get; set; }

        public GlobalaccountRoleCollectionAssignmentArgs()
        {
        }
        public static new GlobalaccountRoleCollectionAssignmentArgs Empty => new GlobalaccountRoleCollectionAssignmentArgs();
    }

    public sealed class GlobalaccountRoleCollectionAssignmentState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the attribute to assign.
        /// </summary>
        [Input("attributeName")]
        public Input<string>? AttributeName { get; set; }

        /// <summary>
        /// The value of the attribute to assign.
        /// </summary>
        [Input("attributeValue")]
        public Input<string>? AttributeValue { get; set; }

        /// <summary>
        /// The name of the group to assign.
        /// </summary>
        [Input("groupName")]
        public Input<string>? GroupName { get; set; }

        /// <summary>
        /// The identity provider that hosts the user or group. The default value is `ldap`.
        /// </summary>
        [Input("origin")]
        public Input<string>? Origin { get; set; }

        /// <summary>
        /// The name of the role collection.
        /// </summary>
        [Input("roleCollectionName")]
        public Input<string>? RoleCollectionName { get; set; }

        /// <summary>
        /// The name of the user to assign.
        /// </summary>
        [Input("userName")]
        public Input<string>? UserName { get; set; }

        public GlobalaccountRoleCollectionAssignmentState()
        {
        }
        public static new GlobalaccountRoleCollectionAssignmentState Empty => new GlobalaccountRoleCollectionAssignmentState();
    }
}
