// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package btp

import (
	"context"
	"reflect"

	"github.com/lechnerc77/pulumi-btp/sdk/go/btp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Gets all roles.
//
// __Further documentation:__
// <https://help.sap.com/docs/btp/sap-business-technology-platform/role-collections-and-roles-in-global-accounts-directories-and-subaccounts>
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lechnerc77/pulumi-btp/sdk/go/btp"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := btp.GetDirectoryRoles(ctx, &btp.GetDirectoryRolesArgs{
//				DirectoryId: "dd005d8b-1fee-4e6b-b6ff-cb9a197b7fe0",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetDirectoryRoles(ctx *pulumi.Context, args *GetDirectoryRolesArgs, opts ...pulumi.InvokeOption) (*GetDirectoryRolesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDirectoryRolesResult
	err := ctx.Invoke("btp:index/getDirectoryRoles:getDirectoryRoles", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDirectoryRoles.
type GetDirectoryRolesArgs struct {
	// The ID of the directory.
	DirectoryId string `pulumi:"directoryId"`
}

// A collection of values returned by getDirectoryRoles.
type GetDirectoryRolesResult struct {
	// The ID of the directory.
	DirectoryId string `pulumi:"directoryId"`
	// The ID of the directory.
	//
	// Deprecated: Use the `directory_id` attribute instead
	Id     string                   `pulumi:"id"`
	Values []GetDirectoryRolesValue `pulumi:"values"`
}

func GetDirectoryRolesOutput(ctx *pulumi.Context, args GetDirectoryRolesOutputArgs, opts ...pulumi.InvokeOption) GetDirectoryRolesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDirectoryRolesResult, error) {
			args := v.(GetDirectoryRolesArgs)
			r, err := GetDirectoryRoles(ctx, &args, opts...)
			var s GetDirectoryRolesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDirectoryRolesResultOutput)
}

// A collection of arguments for invoking getDirectoryRoles.
type GetDirectoryRolesOutputArgs struct {
	// The ID of the directory.
	DirectoryId pulumi.StringInput `pulumi:"directoryId"`
}

func (GetDirectoryRolesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDirectoryRolesArgs)(nil)).Elem()
}

// A collection of values returned by getDirectoryRoles.
type GetDirectoryRolesResultOutput struct{ *pulumi.OutputState }

func (GetDirectoryRolesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDirectoryRolesResult)(nil)).Elem()
}

func (o GetDirectoryRolesResultOutput) ToGetDirectoryRolesResultOutput() GetDirectoryRolesResultOutput {
	return o
}

func (o GetDirectoryRolesResultOutput) ToGetDirectoryRolesResultOutputWithContext(ctx context.Context) GetDirectoryRolesResultOutput {
	return o
}

func (o GetDirectoryRolesResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetDirectoryRolesResult] {
	return pulumix.Output[GetDirectoryRolesResult]{
		OutputState: o.OutputState,
	}
}

// The ID of the directory.
func (o GetDirectoryRolesResultOutput) DirectoryId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDirectoryRolesResult) string { return v.DirectoryId }).(pulumi.StringOutput)
}

// The ID of the directory.
//
// Deprecated: Use the `directory_id` attribute instead
func (o GetDirectoryRolesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDirectoryRolesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDirectoryRolesResultOutput) Values() GetDirectoryRolesValueArrayOutput {
	return o.ApplyT(func(v GetDirectoryRolesResult) []GetDirectoryRolesValue { return v.Values }).(GetDirectoryRolesValueArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDirectoryRolesResultOutput{})
}
