// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package btp

import (
	"github.com/lechnerc77/pulumi-btp/sdk/go/btp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// List all trust configurations that are configured for your global account.
//
// __Tip:__
// You must be viewer or administrator of the global account.
//
// __Further documentation:__
// <https://help.sap.com/docs/btp/sap-business-technology-platform/trust-and-federation-with-identity-providers>
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lechnerc77/pulumi-btp/sdk/go/btp"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := btp.GetGlobalaccountTrustConfigurations(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetGlobalaccountTrustConfigurations(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetGlobalaccountTrustConfigurationsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetGlobalaccountTrustConfigurationsResult
	err := ctx.Invoke("btp:index/getGlobalaccountTrustConfigurations:getGlobalaccountTrustConfigurations", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getGlobalaccountTrustConfigurations.
type GetGlobalaccountTrustConfigurationsResult struct {
	// The ID of the global account.
	//
	// Deprecated: Use the `btp_globalaccount` datasource instead
	Id string `pulumi:"id"`
	// The trust configurations associated with the global account.
	Values []GetGlobalaccountTrustConfigurationsValue `pulumi:"values"`
}
