// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package btp

import (
	"context"
	"reflect"

	"github.com/lechnerc77/pulumi-btp/sdk/go/btp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Shows registered users in a subaccount. Users belong to one of the identity providers (IdPs) of the subaccount.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lechnerc77/pulumi-btp/sdk/go/btp"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := btp.GetSubaccountUser(ctx, &btp.GetSubaccountUserArgs{
//				SubaccountId: "6aa64c2f-38c1-49a9-b2e8-cf9fea769b7f",
//				UserName:     "john.doe@mycompany.com",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = btp.GetSubaccountUser(ctx, &btp.GetSubaccountUserArgs{
//				Origin:       pulumi.StringRef("my-custom-idp"),
//				SubaccountId: "6aa64c2f-38c1-49a9-b2e8-cf9fea769b7f",
//				UserName:     "jane.doe@mycompany.com",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetSubaccountUser(ctx *pulumi.Context, args *GetSubaccountUserArgs, opts ...pulumi.InvokeOption) (*GetSubaccountUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetSubaccountUserResult
	err := ctx.Invoke("btp:index/getSubaccountUser:getSubaccountUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSubaccountUser.
type GetSubaccountUserArgs struct {
	// The identity provider that hosts the user. Only needed for custom identity provider.
	Origin *string `pulumi:"origin"`
	// The ID of the subaccount.
	SubaccountId string `pulumi:"subaccountId"`
	// The username of the user.
	UserName string `pulumi:"userName"`
}

// A collection of values returned by getSubaccountUser.
type GetSubaccountUserResult struct {
	// Shows if the account is still in use.
	Active bool `pulumi:"active"`
	// The e-mail address of the user.
	Email string `pulumi:"email"`
	// The last name of the user.
	FamilyName string `pulumi:"familyName"`
	// The given name of the user.
	GivenName string `pulumi:"givenName"`
	// The ID of the user.
	Id string `pulumi:"id"`
	// The identity provider that hosts the user. Only needed for custom identity provider.
	Origin string `pulumi:"origin"`
	// The set of role collections, which are assigned to the user.
	RoleCollections []string `pulumi:"roleCollections"`
	// The ID of the subaccount.
	SubaccountId string `pulumi:"subaccountId"`
	// The username of the user.
	UserName string `pulumi:"userName"`
	// The verification status of the user.
	Verified bool `pulumi:"verified"`
}

func GetSubaccountUserOutput(ctx *pulumi.Context, args GetSubaccountUserOutputArgs, opts ...pulumi.InvokeOption) GetSubaccountUserResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetSubaccountUserResult, error) {
			args := v.(GetSubaccountUserArgs)
			r, err := GetSubaccountUser(ctx, &args, opts...)
			var s GetSubaccountUserResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetSubaccountUserResultOutput)
}

// A collection of arguments for invoking getSubaccountUser.
type GetSubaccountUserOutputArgs struct {
	// The identity provider that hosts the user. Only needed for custom identity provider.
	Origin pulumi.StringPtrInput `pulumi:"origin"`
	// The ID of the subaccount.
	SubaccountId pulumi.StringInput `pulumi:"subaccountId"`
	// The username of the user.
	UserName pulumi.StringInput `pulumi:"userName"`
}

func (GetSubaccountUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSubaccountUserArgs)(nil)).Elem()
}

// A collection of values returned by getSubaccountUser.
type GetSubaccountUserResultOutput struct{ *pulumi.OutputState }

func (GetSubaccountUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSubaccountUserResult)(nil)).Elem()
}

func (o GetSubaccountUserResultOutput) ToGetSubaccountUserResultOutput() GetSubaccountUserResultOutput {
	return o
}

func (o GetSubaccountUserResultOutput) ToGetSubaccountUserResultOutputWithContext(ctx context.Context) GetSubaccountUserResultOutput {
	return o
}

func (o GetSubaccountUserResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetSubaccountUserResult] {
	return pulumix.Output[GetSubaccountUserResult]{
		OutputState: o.OutputState,
	}
}

// Shows if the account is still in use.
func (o GetSubaccountUserResultOutput) Active() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSubaccountUserResult) bool { return v.Active }).(pulumi.BoolOutput)
}

// The e-mail address of the user.
func (o GetSubaccountUserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubaccountUserResult) string { return v.Email }).(pulumi.StringOutput)
}

// The last name of the user.
func (o GetSubaccountUserResultOutput) FamilyName() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubaccountUserResult) string { return v.FamilyName }).(pulumi.StringOutput)
}

// The given name of the user.
func (o GetSubaccountUserResultOutput) GivenName() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubaccountUserResult) string { return v.GivenName }).(pulumi.StringOutput)
}

// The ID of the user.
func (o GetSubaccountUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubaccountUserResult) string { return v.Id }).(pulumi.StringOutput)
}

// The identity provider that hosts the user. Only needed for custom identity provider.
func (o GetSubaccountUserResultOutput) Origin() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubaccountUserResult) string { return v.Origin }).(pulumi.StringOutput)
}

// The set of role collections, which are assigned to the user.
func (o GetSubaccountUserResultOutput) RoleCollections() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSubaccountUserResult) []string { return v.RoleCollections }).(pulumi.StringArrayOutput)
}

// The ID of the subaccount.
func (o GetSubaccountUserResultOutput) SubaccountId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubaccountUserResult) string { return v.SubaccountId }).(pulumi.StringOutput)
}

// The username of the user.
func (o GetSubaccountUserResultOutput) UserName() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubaccountUserResult) string { return v.UserName }).(pulumi.StringOutput)
}

// The verification status of the user.
func (o GetSubaccountUserResultOutput) Verified() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSubaccountUserResult) bool { return v.Verified }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSubaccountUserResultOutput{})
}
