// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.lechnerc77.pulumi.btp.btp.outputs;

import com.lechnerc77.pulumi.btp.btp.outputs.GetDirectoryRoleCollectionRole;
import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDirectoryRoleCollectionResult {
    /**
     * @return The description of the role collection.
     * 
     */
    private String description;
    /**
     * @return The ID of the directory.
     * 
     */
    private String directoryId;
    /**
     * @return The ID of the directory.
     * 
     * @deprecated
     * Use the `directory_id` attribute instead
     * 
     */
    @Deprecated /* Use the `directory_id` attribute instead */
    private String id;
    /**
     * @return The name of the role collection.
     * 
     */
    private String name;
    /**
     * @return Shows whether the role collection is read-only.
     * 
     */
    private Boolean readOnly;
    private List<GetDirectoryRoleCollectionRole> roles;

    private GetDirectoryRoleCollectionResult() {}
    /**
     * @return The description of the role collection.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The ID of the directory.
     * 
     */
    public String directoryId() {
        return this.directoryId;
    }
    /**
     * @return The ID of the directory.
     * 
     * @deprecated
     * Use the `directory_id` attribute instead
     * 
     */
    @Deprecated /* Use the `directory_id` attribute instead */
    public String id() {
        return this.id;
    }
    /**
     * @return The name of the role collection.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Shows whether the role collection is read-only.
     * 
     */
    public Boolean readOnly() {
        return this.readOnly;
    }
    public List<GetDirectoryRoleCollectionRole> roles() {
        return this.roles;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDirectoryRoleCollectionResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private String directoryId;
        private String id;
        private String name;
        private Boolean readOnly;
        private List<GetDirectoryRoleCollectionRole> roles;
        public Builder() {}
        public Builder(GetDirectoryRoleCollectionResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.directoryId = defaults.directoryId;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.readOnly = defaults.readOnly;
    	      this.roles = defaults.roles;
        }

        @CustomType.Setter
        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }
        @CustomType.Setter
        public Builder directoryId(String directoryId) {
            this.directoryId = Objects.requireNonNull(directoryId);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder readOnly(Boolean readOnly) {
            this.readOnly = Objects.requireNonNull(readOnly);
            return this;
        }
        @CustomType.Setter
        public Builder roles(List<GetDirectoryRoleCollectionRole> roles) {
            this.roles = Objects.requireNonNull(roles);
            return this;
        }
        public Builder roles(GetDirectoryRoleCollectionRole... roles) {
            return roles(List.of(roles));
        }
        public GetDirectoryRoleCollectionResult build() {
            final var _resultValue = new GetDirectoryRoleCollectionResult();
            _resultValue.description = description;
            _resultValue.directoryId = directoryId;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.readOnly = readOnly;
            _resultValue.roles = roles;
            return _resultValue;
        }
    }
}
