// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.lechnerc77.pulumi.btp.btp.outputs;

import com.lechnerc77.pulumi.btp.btp.outputs.GetSubaccountServiceOfferingsValue;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetSubaccountServiceOfferingsResult {
    /**
     * @return Lists services to be consumed in a Cloud Foundry or Kubernetes-native way. Valid values are:
     * 
     */
    private @Nullable String environment;
    private @Nullable String fieldsFilter;
    /**
     * @deprecated
     * Use the `subaccount_id` attribute instead
     * 
     */
    @Deprecated /* Use the `subaccount_id` attribute instead */
    private String id;
    private @Nullable String labelsFilter;
    /**
     * @return The ID of the subaccount.
     * 
     */
    private String subaccountId;
    private List<GetSubaccountServiceOfferingsValue> values;

    private GetSubaccountServiceOfferingsResult() {}
    /**
     * @return Lists services to be consumed in a Cloud Foundry or Kubernetes-native way. Valid values are:
     * 
     */
    public Optional<String> environment() {
        return Optional.ofNullable(this.environment);
    }
    public Optional<String> fieldsFilter() {
        return Optional.ofNullable(this.fieldsFilter);
    }
    /**
     * @deprecated
     * Use the `subaccount_id` attribute instead
     * 
     */
    @Deprecated /* Use the `subaccount_id` attribute instead */
    public String id() {
        return this.id;
    }
    public Optional<String> labelsFilter() {
        return Optional.ofNullable(this.labelsFilter);
    }
    /**
     * @return The ID of the subaccount.
     * 
     */
    public String subaccountId() {
        return this.subaccountId;
    }
    public List<GetSubaccountServiceOfferingsValue> values() {
        return this.values;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSubaccountServiceOfferingsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String environment;
        private @Nullable String fieldsFilter;
        private String id;
        private @Nullable String labelsFilter;
        private String subaccountId;
        private List<GetSubaccountServiceOfferingsValue> values;
        public Builder() {}
        public Builder(GetSubaccountServiceOfferingsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.environment = defaults.environment;
    	      this.fieldsFilter = defaults.fieldsFilter;
    	      this.id = defaults.id;
    	      this.labelsFilter = defaults.labelsFilter;
    	      this.subaccountId = defaults.subaccountId;
    	      this.values = defaults.values;
        }

        @CustomType.Setter
        public Builder environment(@Nullable String environment) {
            this.environment = environment;
            return this;
        }
        @CustomType.Setter
        public Builder fieldsFilter(@Nullable String fieldsFilter) {
            this.fieldsFilter = fieldsFilter;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder labelsFilter(@Nullable String labelsFilter) {
            this.labelsFilter = labelsFilter;
            return this;
        }
        @CustomType.Setter
        public Builder subaccountId(String subaccountId) {
            this.subaccountId = Objects.requireNonNull(subaccountId);
            return this;
        }
        @CustomType.Setter
        public Builder values(List<GetSubaccountServiceOfferingsValue> values) {
            this.values = Objects.requireNonNull(values);
            return this;
        }
        public Builder values(GetSubaccountServiceOfferingsValue... values) {
            return values(List.of(values));
        }
        public GetSubaccountServiceOfferingsResult build() {
            final var _resultValue = new GetSubaccountServiceOfferingsResult();
            _resultValue.environment = environment;
            _resultValue.fieldsFilter = fieldsFilter;
            _resultValue.id = id;
            _resultValue.labelsFilter = labelsFilter;
            _resultValue.subaccountId = subaccountId;
            _resultValue.values = values;
            return _resultValue;
        }
    }
}
