// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.lechnerc77.pulumi.btp.btp.outputs;

import com.lechnerc77.pulumi.btp.btp.outputs.GetSubaccountRoleScope;
import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetSubaccountRoleResult {
    /**
     * @return The ID of the xsuaa application.
     * 
     */
    private String appId;
    /**
     * @return The description of the role.
     * 
     */
    private String description;
    /**
     * @return The ID of the subaccount.
     * 
     * @deprecated
     * Use the `subaccount_id` attribute instead
     * 
     */
    @Deprecated /* Use the `subaccount_id` attribute instead */
    private String id;
    /**
     * @return The name of the role.
     * 
     */
    private String name;
    /**
     * @return Shows whether the role can be modified or not.
     * 
     */
    private Boolean readOnly;
    /**
     * @return The name of the role template.
     * 
     */
    private String roleTemplateName;
    /**
     * @return The scopes available with this role.
     * 
     */
    private List<GetSubaccountRoleScope> scopes;
    /**
     * @return The ID of the subaccount.
     * 
     */
    private String subaccountId;

    private GetSubaccountRoleResult() {}
    /**
     * @return The ID of the xsuaa application.
     * 
     */
    public String appId() {
        return this.appId;
    }
    /**
     * @return The description of the role.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The ID of the subaccount.
     * 
     * @deprecated
     * Use the `subaccount_id` attribute instead
     * 
     */
    @Deprecated /* Use the `subaccount_id` attribute instead */
    public String id() {
        return this.id;
    }
    /**
     * @return The name of the role.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Shows whether the role can be modified or not.
     * 
     */
    public Boolean readOnly() {
        return this.readOnly;
    }
    /**
     * @return The name of the role template.
     * 
     */
    public String roleTemplateName() {
        return this.roleTemplateName;
    }
    /**
     * @return The scopes available with this role.
     * 
     */
    public List<GetSubaccountRoleScope> scopes() {
        return this.scopes;
    }
    /**
     * @return The ID of the subaccount.
     * 
     */
    public String subaccountId() {
        return this.subaccountId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSubaccountRoleResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String appId;
        private String description;
        private String id;
        private String name;
        private Boolean readOnly;
        private String roleTemplateName;
        private List<GetSubaccountRoleScope> scopes;
        private String subaccountId;
        public Builder() {}
        public Builder(GetSubaccountRoleResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.appId = defaults.appId;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.readOnly = defaults.readOnly;
    	      this.roleTemplateName = defaults.roleTemplateName;
    	      this.scopes = defaults.scopes;
    	      this.subaccountId = defaults.subaccountId;
        }

        @CustomType.Setter
        public Builder appId(String appId) {
            this.appId = Objects.requireNonNull(appId);
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder readOnly(Boolean readOnly) {
            this.readOnly = Objects.requireNonNull(readOnly);
            return this;
        }
        @CustomType.Setter
        public Builder roleTemplateName(String roleTemplateName) {
            this.roleTemplateName = Objects.requireNonNull(roleTemplateName);
            return this;
        }
        @CustomType.Setter
        public Builder scopes(List<GetSubaccountRoleScope> scopes) {
            this.scopes = Objects.requireNonNull(scopes);
            return this;
        }
        public Builder scopes(GetSubaccountRoleScope... scopes) {
            return scopes(List.of(scopes));
        }
        @CustomType.Setter
        public Builder subaccountId(String subaccountId) {
            this.subaccountId = Objects.requireNonNull(subaccountId);
            return this;
        }
        public GetSubaccountRoleResult build() {
            final var _resultValue = new GetSubaccountRoleResult();
            _resultValue.appId = appId;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.readOnly = readOnly;
            _resultValue.roleTemplateName = roleTemplateName;
            _resultValue.scopes = scopes;
            _resultValue.subaccountId = subaccountId;
            return _resultValue;
        }
    }
}
