// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.lechnerc77.pulumi.btp.btp;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GlobalaccountRoleCollectionAssignmentArgs extends com.pulumi.resources.ResourceArgs {

    public static final GlobalaccountRoleCollectionAssignmentArgs Empty = new GlobalaccountRoleCollectionAssignmentArgs();

    /**
     * The name of the attribute to assign.
     * 
     */
    @Import(name="attributeName")
    private @Nullable Output<String> attributeName;

    /**
     * @return The name of the attribute to assign.
     * 
     */
    public Optional<Output<String>> attributeName() {
        return Optional.ofNullable(this.attributeName);
    }

    /**
     * The value of the attribute to assign.
     * 
     */
    @Import(name="attributeValue")
    private @Nullable Output<String> attributeValue;

    /**
     * @return The value of the attribute to assign.
     * 
     */
    public Optional<Output<String>> attributeValue() {
        return Optional.ofNullable(this.attributeValue);
    }

    /**
     * The name of the group to assign.
     * 
     */
    @Import(name="groupName")
    private @Nullable Output<String> groupName;

    /**
     * @return The name of the group to assign.
     * 
     */
    public Optional<Output<String>> groupName() {
        return Optional.ofNullable(this.groupName);
    }

    /**
     * The identity provider that hosts the user or group. The default value is `ldap`.
     * 
     */
    @Import(name="origin")
    private @Nullable Output<String> origin;

    /**
     * @return The identity provider that hosts the user or group. The default value is `ldap`.
     * 
     */
    public Optional<Output<String>> origin() {
        return Optional.ofNullable(this.origin);
    }

    /**
     * The name of the role collection.
     * 
     */
    @Import(name="roleCollectionName", required=true)
    private Output<String> roleCollectionName;

    /**
     * @return The name of the role collection.
     * 
     */
    public Output<String> roleCollectionName() {
        return this.roleCollectionName;
    }

    /**
     * The name of the user to assign.
     * 
     */
    @Import(name="userName")
    private @Nullable Output<String> userName;

    /**
     * @return The name of the user to assign.
     * 
     */
    public Optional<Output<String>> userName() {
        return Optional.ofNullable(this.userName);
    }

    private GlobalaccountRoleCollectionAssignmentArgs() {}

    private GlobalaccountRoleCollectionAssignmentArgs(GlobalaccountRoleCollectionAssignmentArgs $) {
        this.attributeName = $.attributeName;
        this.attributeValue = $.attributeValue;
        this.groupName = $.groupName;
        this.origin = $.origin;
        this.roleCollectionName = $.roleCollectionName;
        this.userName = $.userName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GlobalaccountRoleCollectionAssignmentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GlobalaccountRoleCollectionAssignmentArgs $;

        public Builder() {
            $ = new GlobalaccountRoleCollectionAssignmentArgs();
        }

        public Builder(GlobalaccountRoleCollectionAssignmentArgs defaults) {
            $ = new GlobalaccountRoleCollectionAssignmentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param attributeName The name of the attribute to assign.
         * 
         * @return builder
         * 
         */
        public Builder attributeName(@Nullable Output<String> attributeName) {
            $.attributeName = attributeName;
            return this;
        }

        /**
         * @param attributeName The name of the attribute to assign.
         * 
         * @return builder
         * 
         */
        public Builder attributeName(String attributeName) {
            return attributeName(Output.of(attributeName));
        }

        /**
         * @param attributeValue The value of the attribute to assign.
         * 
         * @return builder
         * 
         */
        public Builder attributeValue(@Nullable Output<String> attributeValue) {
            $.attributeValue = attributeValue;
            return this;
        }

        /**
         * @param attributeValue The value of the attribute to assign.
         * 
         * @return builder
         * 
         */
        public Builder attributeValue(String attributeValue) {
            return attributeValue(Output.of(attributeValue));
        }

        /**
         * @param groupName The name of the group to assign.
         * 
         * @return builder
         * 
         */
        public Builder groupName(@Nullable Output<String> groupName) {
            $.groupName = groupName;
            return this;
        }

        /**
         * @param groupName The name of the group to assign.
         * 
         * @return builder
         * 
         */
        public Builder groupName(String groupName) {
            return groupName(Output.of(groupName));
        }

        /**
         * @param origin The identity provider that hosts the user or group. The default value is `ldap`.
         * 
         * @return builder
         * 
         */
        public Builder origin(@Nullable Output<String> origin) {
            $.origin = origin;
            return this;
        }

        /**
         * @param origin The identity provider that hosts the user or group. The default value is `ldap`.
         * 
         * @return builder
         * 
         */
        public Builder origin(String origin) {
            return origin(Output.of(origin));
        }

        /**
         * @param roleCollectionName The name of the role collection.
         * 
         * @return builder
         * 
         */
        public Builder roleCollectionName(Output<String> roleCollectionName) {
            $.roleCollectionName = roleCollectionName;
            return this;
        }

        /**
         * @param roleCollectionName The name of the role collection.
         * 
         * @return builder
         * 
         */
        public Builder roleCollectionName(String roleCollectionName) {
            return roleCollectionName(Output.of(roleCollectionName));
        }

        /**
         * @param userName The name of the user to assign.
         * 
         * @return builder
         * 
         */
        public Builder userName(@Nullable Output<String> userName) {
            $.userName = userName;
            return this;
        }

        /**
         * @param userName The name of the user to assign.
         * 
         * @return builder
         * 
         */
        public Builder userName(String userName) {
            return userName(Output.of(userName));
        }

        public GlobalaccountRoleCollectionAssignmentArgs build() {
            $.roleCollectionName = Objects.requireNonNull($.roleCollectionName, "expected parameter 'roleCollectionName' to be non-null");
            return $;
        }
    }

}
