// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.lechnerc77.pulumi.btp.btp;

import com.lechnerc77.pulumi.btp.btp.GlobalaccountResourceProviderArgs;
import com.lechnerc77.pulumi.btp.btp.Utilities;
import com.lechnerc77.pulumi.btp.btp.inputs.GlobalaccountResourceProviderState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * Creates a resource provider instance to allow your global account to connect to your provider account on a non-SAP cloud vendor. Through this channel, you can consume remote service resources that you already own and are supported by SAP BTP.
 * For example, if you are subscribed to Amazon Web Services (AWS) and have already purchased services, such as PostgreSQL, you can register the vendor as a resource provider in SAP BTP and consume this service across your subaccounts together with other services offered by SAP.
 * 
 * The use of this functionality is subject to the availability of the supported non-SAP cloud vendors in your country/region.
 * 
 * __Tips:__
 * * You must be assigned to the global account admin role.
 * * You can create more than one instance of a given resource provider, each with its unique configuration properties. In such cases, the display name and technical name should be descriptive enough so that you and developers can easily differentiate between each instance.
 * * After you configure a new resource provider instance, its supported services are added as entitlements in your global account.
 * 
 * __Further documentation:__
 * &lt;https://help.sap.com/docs/btp/sap-business-technology-platform/managing-resource-providers&gt;
 * 
 * ## Example Usage
 * 
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.btp.GlobalaccountResourceProvider;
 * import com.pulumi.btp.GlobalaccountResourceProviderArgs;
 * import static com.pulumi.codegen.internal.Serialization.*;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var azure = new GlobalaccountResourceProvider(&#34;azure&#34;, GlobalaccountResourceProviderArgs.builder()        
 *             .id(&#34;my_azure_provider&#34;)
 *             .resourceProvider(&#34;AZURE&#34;)
 *             .parameters(serializeJson(
 *                 jsonObject(
 *                     jsonProperty(&#34;region&#34;, &#34;westeurope&#34;),
 *                     jsonProperty(&#34;client_id&#34;, &#34;AZURECLIENTID&#34;),
 *                     jsonProperty(&#34;client_secret&#34;, &#34;AZURECLIENTSECRET&#34;),
 *                     jsonProperty(&#34;tenant_id&#34;, &#34;42x7676x-f455-423x-82x6-xx2d99791xx7&#34;),
 *                     jsonProperty(&#34;subscription_id&#34;, &#34;x1x9567x-8560-44xx-x4fx-741xx0x08x58&#34;),
 *                     jsonProperty(&#34;resource_group_name&#34;, &#34;rg-landscape-azure-example&#34;)
 *                 )))
 *             .build());
 * 
 *         var aws = new GlobalaccountResourceProvider(&#34;aws&#34;, GlobalaccountResourceProviderArgs.builder()        
 *             .id(&#34;my_aws_provider&#34;)
 *             .resourceProvider(&#34;AWS&#34;)
 *             .parameters(serializeJson(
 *                 jsonObject(
 *                     jsonProperty(&#34;access_key_id&#34;, &#34;AWSACCESSKEY&#34;),
 *                     jsonProperty(&#34;secret_access_key&#34;, &#34;AWSSECRETKEY&#34;),
 *                     jsonProperty(&#34;vpc_id&#34;, &#34;vpc-test&#34;),
 *                     jsonProperty(&#34;region&#34;, &#34;eu-central-1&#34;)
 *                 )))
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * terraform
 * 
 * ```sh
 *  $ pulumi import btp:index/globalaccountResourceProvider:GlobalaccountResourceProvider &lt;resource_name&gt; &lt;resource_provider&gt;,&lt;unique_technical_name&gt;
 * ```
 * 
 * ```sh
 *  $ pulumi import btp:index/globalaccountResourceProvider:GlobalaccountResourceProvider azure AZURE,my_azure_provider
 * ```
 * 
 */
@ResourceType(type="btp:index/globalaccountResourceProvider:GlobalaccountResourceProvider")
public class GlobalaccountResourceProvider extends com.pulumi.resources.CustomResource {
    /**
     * The configuration properties for the resource provider as required by the vendor.
     * 
     */
    @Export(name="configuration", refs={String.class}, tree="[0]")
    private Output<String> configuration;

    /**
     * @return The configuration properties for the resource provider as required by the vendor.
     * 
     */
    public Output<String> configuration() {
        return this.configuration;
    }
    /**
     * The description of the resource provider.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output<String> description;

    /**
     * @return The description of the resource provider.
     * 
     */
    public Output<String> description() {
        return this.description;
    }
    /**
     * The descriptive name of the resource provider.
     * 
     */
    @Export(name="displayName", refs={String.class}, tree="[0]")
    private Output<String> displayName;

    /**
     * @return The descriptive name of the resource provider.
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }
    /**
     * The cloud vendor from which to consume services through your subscribed account. Possible values are:
     * 
     */
    @Export(name="providerType", refs={String.class}, tree="[0]")
    private Output<String> providerType;

    /**
     * @return The cloud vendor from which to consume services through your subscribed account. Possible values are:
     * 
     */
    public Output<String> providerType() {
        return this.providerType;
    }
    /**
     * The unique technical name of the resource provider.
     * 
     */
    @Export(name="technicalName", refs={String.class}, tree="[0]")
    private Output<String> technicalName;

    /**
     * @return The unique technical name of the resource provider.
     * 
     */
    public Output<String> technicalName() {
        return this.technicalName;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public GlobalaccountResourceProvider(String name) {
        this(name, GlobalaccountResourceProviderArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public GlobalaccountResourceProvider(String name, GlobalaccountResourceProviderArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public GlobalaccountResourceProvider(String name, GlobalaccountResourceProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("btp:index/globalaccountResourceProvider:GlobalaccountResourceProvider", name, args == null ? GlobalaccountResourceProviderArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private GlobalaccountResourceProvider(String name, Output<String> id, @Nullable GlobalaccountResourceProviderState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("btp:index/globalaccountResourceProvider:GlobalaccountResourceProvider", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "configuration"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static GlobalaccountResourceProvider get(String name, Output<String> id, @Nullable GlobalaccountResourceProviderState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new GlobalaccountResourceProvider(name, id, state, options);
    }
}
