// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.lechnerc77.pulumi.btp.btp.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetDirectoryRoleCollectionPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDirectoryRoleCollectionPlainArgs Empty = new GetDirectoryRoleCollectionPlainArgs();

    /**
     * The ID of the directory.
     * 
     */
    @Import(name="directoryId", required=true)
    private String directoryId;

    /**
     * @return The ID of the directory.
     * 
     */
    public String directoryId() {
        return this.directoryId;
    }

    /**
     * The name of the role collection.
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return The name of the role collection.
     * 
     */
    public String name() {
        return this.name;
    }

    private GetDirectoryRoleCollectionPlainArgs() {}

    private GetDirectoryRoleCollectionPlainArgs(GetDirectoryRoleCollectionPlainArgs $) {
        this.directoryId = $.directoryId;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDirectoryRoleCollectionPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDirectoryRoleCollectionPlainArgs $;

        public Builder() {
            $ = new GetDirectoryRoleCollectionPlainArgs();
        }

        public Builder(GetDirectoryRoleCollectionPlainArgs defaults) {
            $ = new GetDirectoryRoleCollectionPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param directoryId The ID of the directory.
         * 
         * @return builder
         * 
         */
        public Builder directoryId(String directoryId) {
            $.directoryId = directoryId;
            return this;
        }

        /**
         * @param name The name of the role collection.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public GetDirectoryRoleCollectionPlainArgs build() {
            $.directoryId = Objects.requireNonNull($.directoryId, "expected parameter 'directoryId' to be non-null");
            $.name = Objects.requireNonNull($.name, "expected parameter 'name' to be non-null");
            return $;
        }
    }

}
