// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.lechnerc77.pulumi.btp.btp.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetSubaccountServiceOfferingsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSubaccountServiceOfferingsArgs Empty = new GetSubaccountServiceOfferingsArgs();

    /**
     * Lists services to be consumed in a Cloud Foundry or Kubernetes-native way. Valid values are:
     * 
     */
    @Import(name="environment")
    private @Nullable Output<String> environment;

    /**
     * @return Lists services to be consumed in a Cloud Foundry or Kubernetes-native way. Valid values are:
     * 
     */
    public Optional<Output<String>> environment() {
        return Optional.ofNullable(this.environment);
    }

    @Import(name="fieldsFilter")
    private @Nullable Output<String> fieldsFilter;

    public Optional<Output<String>> fieldsFilter() {
        return Optional.ofNullable(this.fieldsFilter);
    }

    @Import(name="labelsFilter")
    private @Nullable Output<String> labelsFilter;

    public Optional<Output<String>> labelsFilter() {
        return Optional.ofNullable(this.labelsFilter);
    }

    /**
     * The ID of the subaccount.
     * 
     */
    @Import(name="subaccountId", required=true)
    private Output<String> subaccountId;

    /**
     * @return The ID of the subaccount.
     * 
     */
    public Output<String> subaccountId() {
        return this.subaccountId;
    }

    private GetSubaccountServiceOfferingsArgs() {}

    private GetSubaccountServiceOfferingsArgs(GetSubaccountServiceOfferingsArgs $) {
        this.environment = $.environment;
        this.fieldsFilter = $.fieldsFilter;
        this.labelsFilter = $.labelsFilter;
        this.subaccountId = $.subaccountId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSubaccountServiceOfferingsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSubaccountServiceOfferingsArgs $;

        public Builder() {
            $ = new GetSubaccountServiceOfferingsArgs();
        }

        public Builder(GetSubaccountServiceOfferingsArgs defaults) {
            $ = new GetSubaccountServiceOfferingsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param environment Lists services to be consumed in a Cloud Foundry or Kubernetes-native way. Valid values are:
         * 
         * @return builder
         * 
         */
        public Builder environment(@Nullable Output<String> environment) {
            $.environment = environment;
            return this;
        }

        /**
         * @param environment Lists services to be consumed in a Cloud Foundry or Kubernetes-native way. Valid values are:
         * 
         * @return builder
         * 
         */
        public Builder environment(String environment) {
            return environment(Output.of(environment));
        }

        public Builder fieldsFilter(@Nullable Output<String> fieldsFilter) {
            $.fieldsFilter = fieldsFilter;
            return this;
        }

        public Builder fieldsFilter(String fieldsFilter) {
            return fieldsFilter(Output.of(fieldsFilter));
        }

        public Builder labelsFilter(@Nullable Output<String> labelsFilter) {
            $.labelsFilter = labelsFilter;
            return this;
        }

        public Builder labelsFilter(String labelsFilter) {
            return labelsFilter(Output.of(labelsFilter));
        }

        /**
         * @param subaccountId The ID of the subaccount.
         * 
         * @return builder
         * 
         */
        public Builder subaccountId(Output<String> subaccountId) {
            $.subaccountId = subaccountId;
            return this;
        }

        /**
         * @param subaccountId The ID of the subaccount.
         * 
         * @return builder
         * 
         */
        public Builder subaccountId(String subaccountId) {
            return subaccountId(Output.of(subaccountId));
        }

        public GetSubaccountServiceOfferingsArgs build() {
            $.subaccountId = Objects.requireNonNull($.subaccountId, "expected parameter 'subaccountId' to be non-null");
            return $;
        }
    }

}
