// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.lechnerc77.pulumi.btp.btp.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetSubaccountSubscriptionsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSubaccountSubscriptionsPlainArgs Empty = new GetSubaccountSubscriptionsPlainArgs();

    @Import(name="subaccountId", required=true)
    private String subaccountId;

    public String subaccountId() {
        return this.subaccountId;
    }

    private GetSubaccountSubscriptionsPlainArgs() {}

    private GetSubaccountSubscriptionsPlainArgs(GetSubaccountSubscriptionsPlainArgs $) {
        this.subaccountId = $.subaccountId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSubaccountSubscriptionsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSubaccountSubscriptionsPlainArgs $;

        public Builder() {
            $ = new GetSubaccountSubscriptionsPlainArgs();
        }

        public Builder(GetSubaccountSubscriptionsPlainArgs defaults) {
            $ = new GetSubaccountSubscriptionsPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder subaccountId(String subaccountId) {
            $.subaccountId = subaccountId;
            return this;
        }

        public GetSubaccountSubscriptionsPlainArgs build() {
            $.subaccountId = Objects.requireNonNull($.subaccountId, "expected parameter 'subaccountId' to be non-null");
            return $;
        }
    }

}
