// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.lechnerc77.pulumi.btp.btp.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetSubaccountServiceInstancesPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSubaccountServiceInstancesPlainArgs Empty = new GetSubaccountServiceInstancesPlainArgs();

    /**
     * Filters the instances based on their fields. For example, to list all instances that are usable, use &#34;usable eq &#39;true&#39;&#34;.
     * 
     */
    @Import(name="fieldsFilter")
    private @Nullable String fieldsFilter;

    /**
     * @return Filters the instances based on their fields. For example, to list all instances that are usable, use &#34;usable eq &#39;true&#39;&#34;.
     * 
     */
    public Optional<String> fieldsFilter() {
        return Optional.ofNullable(this.fieldsFilter);
    }

    /**
     * Filters the instances based on the label query.  For example, to list all instances that are available in a production landscape, use &#34;landscape eq &#39;production&#39;&#34;.
     * 
     */
    @Import(name="labelsFilter")
    private @Nullable String labelsFilter;

    /**
     * @return Filters the instances based on the label query.  For example, to list all instances that are available in a production landscape, use &#34;landscape eq &#39;production&#39;&#34;.
     * 
     */
    public Optional<String> labelsFilter() {
        return Optional.ofNullable(this.labelsFilter);
    }

    /**
     * The ID of the subaccount.
     * 
     */
    @Import(name="subaccountId", required=true)
    private String subaccountId;

    /**
     * @return The ID of the subaccount.
     * 
     */
    public String subaccountId() {
        return this.subaccountId;
    }

    private GetSubaccountServiceInstancesPlainArgs() {}

    private GetSubaccountServiceInstancesPlainArgs(GetSubaccountServiceInstancesPlainArgs $) {
        this.fieldsFilter = $.fieldsFilter;
        this.labelsFilter = $.labelsFilter;
        this.subaccountId = $.subaccountId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSubaccountServiceInstancesPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSubaccountServiceInstancesPlainArgs $;

        public Builder() {
            $ = new GetSubaccountServiceInstancesPlainArgs();
        }

        public Builder(GetSubaccountServiceInstancesPlainArgs defaults) {
            $ = new GetSubaccountServiceInstancesPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param fieldsFilter Filters the instances based on their fields. For example, to list all instances that are usable, use &#34;usable eq &#39;true&#39;&#34;.
         * 
         * @return builder
         * 
         */
        public Builder fieldsFilter(@Nullable String fieldsFilter) {
            $.fieldsFilter = fieldsFilter;
            return this;
        }

        /**
         * @param labelsFilter Filters the instances based on the label query.  For example, to list all instances that are available in a production landscape, use &#34;landscape eq &#39;production&#39;&#34;.
         * 
         * @return builder
         * 
         */
        public Builder labelsFilter(@Nullable String labelsFilter) {
            $.labelsFilter = labelsFilter;
            return this;
        }

        /**
         * @param subaccountId The ID of the subaccount.
         * 
         * @return builder
         * 
         */
        public Builder subaccountId(String subaccountId) {
            $.subaccountId = subaccountId;
            return this;
        }

        public GetSubaccountServiceInstancesPlainArgs build() {
            $.subaccountId = Objects.requireNonNull($.subaccountId, "expected parameter 'subaccountId' to be non-null");
            return $;
        }
    }

}
