// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiBtp.Btp.Inputs
{

    public sealed class SubaccountEnvironmentInstanceTimeoutsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Timeout for creating the environment instance.
        /// </summary>
        [Input("create")]
        public Input<string>? Create { get; set; }

        /// <summary>
        /// Timeout for deleting the environment instance.
        /// </summary>
        [Input("delete")]
        public Input<string>? Delete { get; set; }

        /// <summary>
        /// Timeout for updating the environment instance.
        /// </summary>
        [Input("update")]
        public Input<string>? Update { get; set; }

        public SubaccountEnvironmentInstanceTimeoutsArgs()
        {
        }
        public static new SubaccountEnvironmentInstanceTimeoutsArgs Empty => new SubaccountEnvironmentInstanceTimeoutsArgs();
    }
}
