// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Gets details about a specific app.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as btp from "@pulumi/btp";
 *
 * const byId = btp.getSubaccountApp({
 *     id: "xsuaa!t1",
 *     subaccountId: "6aa64c2f-38c1-49a9-b2e8-cf9fea769b7f",
 * });
 * ```
 */
export function getSubaccountApp(args: GetSubaccountAppArgs, opts?: pulumi.InvokeOptions): Promise<GetSubaccountAppResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("btp:index/getSubaccountApp:getSubaccountApp", {
        "id": args.id,
        "subaccountId": args.subaccountId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSubaccountApp.
 */
export interface GetSubaccountAppArgs {
    /**
     * The application ID is the xsappname plus the identifier, which consists of an exclamation mark (!), an identifier for the plan under which the application is deployed, and an index number.
     */
    id: string;
    /**
     * The ID of the subaccount.
     */
    subaccountId: string;
}

/**
 * A collection of values returned by getSubaccountApp.
 */
export interface GetSubaccountAppResult {
    readonly authorities: string[];
    /**
     * The description of the app.
     */
    readonly description: string;
    readonly foreignScopeReferences: string[];
    /**
     * The application ID is the xsappname plus the identifier, which consists of an exclamation mark (!), an identifier for the plan under which the application is deployed, and an index number.
     */
    readonly id: string;
    readonly masterAppId: string;
    readonly oauth2Configuration: outputs.GetSubaccountAppOauth2Configuration;
    readonly orgId: string;
    readonly planId: string;
    readonly planName: string;
    readonly serviceinstanceId: string;
    readonly spaceId: string;
    /**
     * The ID of the subaccount.
     */
    readonly subaccountId: string;
    readonly tenantMode: string;
    readonly username: string;
    readonly xsappname: string;
}
/**
 * Gets details about a specific app.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as btp from "@pulumi/btp";
 *
 * const byId = btp.getSubaccountApp({
 *     id: "xsuaa!t1",
 *     subaccountId: "6aa64c2f-38c1-49a9-b2e8-cf9fea769b7f",
 * });
 * ```
 */
export function getSubaccountAppOutput(args: GetSubaccountAppOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSubaccountAppResult> {
    return pulumi.output(args).apply((a: any) => getSubaccountApp(a, opts))
}

/**
 * A collection of arguments for invoking getSubaccountApp.
 */
export interface GetSubaccountAppOutputArgs {
    /**
     * The application ID is the xsappname plus the identifier, which consists of an exclamation mark (!), an identifier for the plan under which the application is deployed, and an index number.
     */
    id: pulumi.Input<string>;
    /**
     * The ID of the subaccount.
     */
    subaccountId: pulumi.Input<string>;
}
