// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Gets the details of a specific environment instance in a subaccount.
 *
 * __Tip:__
 * You must be assigned to the subaccount admin or viewer role.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as btp from "@pulumi/btp";
 *
 * const cloudfoundry = btp.getSubaccountEnvironmentInstance({
 *     id: "6D079379-6442-464A-90EB-65FAC05B176F",
 *     subaccountId: "6aa64c2f-38c1-49a9-b2e8-cf9fea769b7f",
 * });
 * ```
 */
export function getSubaccountEnvironmentInstance(args: GetSubaccountEnvironmentInstanceArgs, opts?: pulumi.InvokeOptions): Promise<GetSubaccountEnvironmentInstanceResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("btp:index/getSubaccountEnvironmentInstance:getSubaccountEnvironmentInstance", {
        "id": args.id,
        "subaccountId": args.subaccountId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSubaccountEnvironmentInstance.
 */
export interface GetSubaccountEnvironmentInstanceArgs {
    /**
     * The ID of the environment instance.
     */
    id: string;
    /**
     * The ID of the subaccount.
     */
    subaccountId: string;
}

/**
 * A collection of values returned by getSubaccountEnvironmentInstance.
 */
export interface GetSubaccountEnvironmentInstanceResult {
    /**
     * The ID of the associated environment broker.
     */
    readonly brokerId: string;
    /**
     * The date and time when the resource was created in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) format.
     */
    readonly createdDate: string;
    readonly customLabels: {[key: string]: string[]};
    /**
     * The URL of the service dashboard, which is a web-based management user interface for the service instances.
     */
    readonly dashboardUrl: string;
    /**
     * The description of the environment instance.
     */
    readonly description: string;
    /**
     * The type of the environment instance that is used.
     */
    readonly environmentType: string;
    /**
     * The ID of the environment instance.
     */
    readonly id: string;
    /**
     * The set of words or phrases assigned to the environment instance.
     */
    readonly labels: string;
    /**
     * The name of the landscape within the logged-in region on which the environment instance is created.
     */
    readonly landscapeLabel: string;
    /**
     * The date and time when the resource was last modified in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) format.
     */
    readonly lastModified: string;
    /**
     * The name of the environment instance.
     */
    readonly name: string;
    /**
     * An identifier that represents the last operation. This ID is returned by the environment brokers.
     */
    readonly operation: string;
    /**
     * The configuration parameters for the environment instance.
     */
    readonly parameters: string;
    /**
     * The ID of the service plan for the environment instance in the corresponding service broker's catalog.
     */
    readonly planId: string;
    /**
     * The name of the service plan for the environment instance in the corresponding service broker's catalog.
     */
    readonly planName: string;
    /**
     * The ID of the platform for the environment instance in the corresponding service broker's catalog.
     */
    readonly platformId: string;
    /**
     * The ID of the service for the environment instance in the corresponding service broker's catalog.
     */
    readonly serviceId: string;
    /**
     * The name of the service for the environment instance in the corresponding service broker's catalog.
     */
    readonly serviceName: string;
    /**
     * The current state of the environment instance. Possible values are:
     */
    readonly state: string;
    /**
     * The ID of the subaccount.
     */
    readonly subaccountId: string;
    readonly tenantId: string;
    readonly type: string;
}
/**
 * Gets the details of a specific environment instance in a subaccount.
 *
 * __Tip:__
 * You must be assigned to the subaccount admin or viewer role.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as btp from "@pulumi/btp";
 *
 * const cloudfoundry = btp.getSubaccountEnvironmentInstance({
 *     id: "6D079379-6442-464A-90EB-65FAC05B176F",
 *     subaccountId: "6aa64c2f-38c1-49a9-b2e8-cf9fea769b7f",
 * });
 * ```
 */
export function getSubaccountEnvironmentInstanceOutput(args: GetSubaccountEnvironmentInstanceOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSubaccountEnvironmentInstanceResult> {
    return pulumi.output(args).apply((a: any) => getSubaccountEnvironmentInstance(a, opts))
}

/**
 * A collection of arguments for invoking getSubaccountEnvironmentInstance.
 */
export interface GetSubaccountEnvironmentInstanceOutputArgs {
    /**
     * The ID of the environment instance.
     */
    id: pulumi.Input<string>;
    /**
     * The ID of the subaccount.
     */
    subaccountId: pulumi.Input<string>;
}
