// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Gets details about a specific subaccount role collection.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as btp from "@pulumi/btp";
 *
 * const subaccountAdmin = btp.getSubaccountRoleCollection({
 *     name: "Subaccount Administrator",
 *     subaccountId: "6aa64c2f-38c1-49a9-b2e8-cf9fea769b7f",
 * });
 * ```
 */
export function getSubaccountRoleCollection(args: GetSubaccountRoleCollectionArgs, opts?: pulumi.InvokeOptions): Promise<GetSubaccountRoleCollectionResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("btp:index/getSubaccountRoleCollection:getSubaccountRoleCollection", {
        "name": args.name,
        "subaccountId": args.subaccountId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSubaccountRoleCollection.
 */
export interface GetSubaccountRoleCollectionArgs {
    /**
     * The name of the role collection.
     */
    name: string;
    /**
     * The ID of the subaccount.
     */
    subaccountId: string;
}

/**
 * A collection of values returned by getSubaccountRoleCollection.
 */
export interface GetSubaccountRoleCollectionResult {
    /**
     * The description of the role collection.
     */
    readonly description: string;
    /**
     * The ID of the subaccount.
     *
     * @deprecated Use the `subaccount_id` attribute instead
     */
    readonly id: string;
    /**
     * The name of the role collection.
     */
    readonly name: string;
    /**
     * Shows whether the role collection is read-only.
     */
    readonly readOnly: boolean;
    readonly roles: outputs.GetSubaccountRoleCollectionRole[];
    /**
     * The ID of the subaccount.
     */
    readonly subaccountId: string;
}
/**
 * Gets details about a specific subaccount role collection.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as btp from "@pulumi/btp";
 *
 * const subaccountAdmin = btp.getSubaccountRoleCollection({
 *     name: "Subaccount Administrator",
 *     subaccountId: "6aa64c2f-38c1-49a9-b2e8-cf9fea769b7f",
 * });
 * ```
 */
export function getSubaccountRoleCollectionOutput(args: GetSubaccountRoleCollectionOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSubaccountRoleCollectionResult> {
    return pulumi.output(args).apply((a: any) => getSubaccountRoleCollection(a, opts))
}

/**
 * A collection of arguments for invoking getSubaccountRoleCollection.
 */
export interface GetSubaccountRoleCollectionOutputArgs {
    /**
     * The name of the role collection.
     */
    name: pulumi.Input<string>;
    /**
     * The ID of the subaccount.
     */
    subaccountId: pulumi.Input<string>;
}
