// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Sets the security settings of a global account.
 *
 * __Tip:__
 * You must be administrator of the global account.
 *
 * __Further documentation:__
 * <https://help.sap.com/docs/btp/sap-business-technology-platform/configure-trusted-domains-for-sap-authorization-and-trust-management-service>
 * <https://help.sap.com/docs/btp/sap-business-technology-platform/configure-token-policy-for-sap-authorization-and-trust-management-service>
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as btp from "@lechnerc77/pulumi-btp";
 *
 * const _this = new btp.GlobalaccountSecuritySettings("this", {
 *     accessTokenValidity: 3600,
 *     customEmailDomains: ["yourdomain.test"],
 *     defaultIdentityProvider: "sap.custom",
 *     refreshTokenValidity: 3600,
 *     treatUsersWithSameEmailAsSameUser: true,
 * });
 * ```
 */
export class GlobalaccountSecuritySettings extends pulumi.CustomResource {
    /**
     * Get an existing GlobalaccountSecuritySettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GlobalaccountSecuritySettingsState, opts?: pulumi.CustomResourceOptions): GlobalaccountSecuritySettings {
        return new GlobalaccountSecuritySettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'btp:index/globalaccountSecuritySettings:GlobalaccountSecuritySettings';

    /**
     * Returns true if the given object is an instance of GlobalaccountSecuritySettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GlobalaccountSecuritySettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GlobalaccountSecuritySettings.__pulumiType;
    }

    /**
     * The validity of the access token.
     */
    public readonly accessTokenValidity!: pulumi.Output<number>;
    /**
     * Set of domains that are allowed to be used for user authentication.
     */
    public readonly customEmailDomains!: pulumi.Output<string[]>;
    /**
     * The global account's default identity provider for platform users. Used to log on to platform tools such as SAP BTP cockpit or the btp CLI.
     */
    public readonly defaultIdentityProvider!: pulumi.Output<string>;
    /**
     * The validity of the refresh token.
     */
    public readonly refreshTokenValidity!: pulumi.Output<number>;
    /**
     * If set to true, users with the same email are treated as same users.
     */
    public readonly treatUsersWithSameEmailAsSameUser!: pulumi.Output<boolean>;

    /**
     * Create a GlobalaccountSecuritySettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GlobalaccountSecuritySettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GlobalaccountSecuritySettingsArgs | GlobalaccountSecuritySettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GlobalaccountSecuritySettingsState | undefined;
            resourceInputs["accessTokenValidity"] = state ? state.accessTokenValidity : undefined;
            resourceInputs["customEmailDomains"] = state ? state.customEmailDomains : undefined;
            resourceInputs["defaultIdentityProvider"] = state ? state.defaultIdentityProvider : undefined;
            resourceInputs["refreshTokenValidity"] = state ? state.refreshTokenValidity : undefined;
            resourceInputs["treatUsersWithSameEmailAsSameUser"] = state ? state.treatUsersWithSameEmailAsSameUser : undefined;
        } else {
            const args = argsOrState as GlobalaccountSecuritySettingsArgs | undefined;
            resourceInputs["accessTokenValidity"] = args ? args.accessTokenValidity : undefined;
            resourceInputs["customEmailDomains"] = args ? args.customEmailDomains : undefined;
            resourceInputs["defaultIdentityProvider"] = args ? args.defaultIdentityProvider : undefined;
            resourceInputs["refreshTokenValidity"] = args ? args.refreshTokenValidity : undefined;
            resourceInputs["treatUsersWithSameEmailAsSameUser"] = args ? args.treatUsersWithSameEmailAsSameUser : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GlobalaccountSecuritySettings.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GlobalaccountSecuritySettings resources.
 */
export interface GlobalaccountSecuritySettingsState {
    /**
     * The validity of the access token.
     */
    accessTokenValidity?: pulumi.Input<number>;
    /**
     * Set of domains that are allowed to be used for user authentication.
     */
    customEmailDomains?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The global account's default identity provider for platform users. Used to log on to platform tools such as SAP BTP cockpit or the btp CLI.
     */
    defaultIdentityProvider?: pulumi.Input<string>;
    /**
     * The validity of the refresh token.
     */
    refreshTokenValidity?: pulumi.Input<number>;
    /**
     * If set to true, users with the same email are treated as same users.
     */
    treatUsersWithSameEmailAsSameUser?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a GlobalaccountSecuritySettings resource.
 */
export interface GlobalaccountSecuritySettingsArgs {
    /**
     * The validity of the access token.
     */
    accessTokenValidity?: pulumi.Input<number>;
    /**
     * Set of domains that are allowed to be used for user authentication.
     */
    customEmailDomains?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The global account's default identity provider for platform users. Used to log on to platform tools such as SAP BTP cockpit or the btp CLI.
     */
    defaultIdentityProvider?: pulumi.Input<string>;
    /**
     * The validity of the refresh token.
     */
    refreshTokenValidity?: pulumi.Input<number>;
    /**
     * If set to true, users with the same email are treated as same users.
     */
    treatUsersWithSameEmailAsSameUser?: pulumi.Input<boolean>;
}
